### ISSUE TITLE
TypeError in Pandas 2.0.1

### ISSUE THREAD

**Issue by berland** [equinor/res2df#448]
This line is not compatible with Pandas 2.0.1:

https://github.com/equinor/ecl2df/blob/744394994eafb60014d6b7436c39339cf8894957/ecl2df/rft.py#L617

Fails with:
```
Traceback (most recent call last):
  File "/work/venv/newer/bin/ecl2csv", line 33, in <module>
    sys.exit(load_entry_point('ecl2df', 'console_scripts', 'ecl2csv')())
  File "/work/projects/ecl2df/ecl2df/ecl2csv.py", line 315, in main
    args.func(args)
  File "/work/projects/ecl2df/ecl2df/ecl2csv.py", line 306, in run_subparser_main
    main_func(args)
  File "/work/projects/ecl2df/ecl2df/rft.py", line 685, in rft_main
    rft_df = df(eclfiles, wellname=args.wellname, date=args.date)
  File "/work/projects/ecl2df/ecl2df/rft.py", line 617, in df
    con_icd_seg = con_icd_seg[set(con_icd_seg.columns) - delete_cols]
  File "/work/venv/newer/lib64/python3.8/site-packages/pandas/core/frame.py", line 3714, in __getitem__
    check_dict_or_set_indexers(key)
  File "/work/venv/newer/lib64/python3.8/site-packages/pandas/core/indexing.py", line 2611, in check_dict_or_set_indexers
    raise TypeError(
TypeError: Passing a set as an indexer is not supported. Use a list instead.
```
(at least when running `pytst test_ert_hooks.py`)

**Comment by alifbe** [comment]
@berland Convert the set to list will fix the issue. But still a lot other issues come up with pandas 2.0

```python
        con_icd_seg = con_icd_seg[list(set(con_icd_seg.columns) - delete_cols)]
```

**Comment by berland** [comment]
Closing, not reproducible with current `master`
